# Generated by Django 2.1.4 on 2019-01-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTime',
        ),
        migrations.AddField(
            model_name='user',
            name='mins_left',
            field=models.FloatField(blank='true', default=0.48014757181339984, null='true'),
            preserve_default='true',
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank='true', null='true', upload_to=''),
        ),
    ]
