# Generated by Django 2.1.4 on 2019-01-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20190106_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mins_left',
            field=models.FloatField(blank='true', default=69, null='true'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='00000', max_length=30),
        ),
    ]
