# Generated by Django 2.1.4 on 2019-01-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20190106_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mins_left',
            field=models.FloatField(blank='true', default=47, null='true'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='0076', max_length=30),
        ),
    ]
