# Generated by Django 2.1.4 on 2019-01-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20190106_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mins_left',
            field=models.FloatField(blank='true', default=80, null='true'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='00s76', max_length=30),
        ),
    ]
