# Generated by Django 2.1.4 on 2019-01-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20190106_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mins_left',
            field=models.FloatField(blank='true', default=60, null='true'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=43, max_length=30),
        ),
    ]
