# Generated by Django 2.1.4 on 2019-01-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20190106_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='pass2',
            field=models.CharField(default='qwe', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='mins_left',
            field=models.FloatField(blank='true', default=3, null='true'),
        ),
    ]
