# Generated by Django 2.1.4 on 2019-01-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_auto_20190106_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pass2',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='mins_left',
            field=models.FloatField(blank='true', default=94, null='true'),
        ),
    ]
