# Generated by Django 2.1.4 on 2019-01-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_auto_20190106_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='pass2',
            field=models.CharField(default='qwe', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='mins_left',
            field=models.FloatField(blank='true', default=84, null='true'),
        ),
    ]
