# Generated by Django 2.1.4 on 2019-01-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0022_auto_20190107_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mins_left',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='real_name',
        ),
    ]
