# Generated by Django 2.1.4 on 2019-01-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0023_auto_20190107_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='you', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='something@someone.com', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mins_left',
            field=models.FloatField(blank='true', default=74, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank='true', null='true', upload_to=''),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='You', max_length=120),
            preserve_default=False,
        ),
    ]
