# Generated by Django 2.1.4 on 2019-01-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0025_auto_20190107_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mins_left',
            field=models.FloatField(blank='true', default=50, null='true'),
        ),
    ]
