# Generated by Django 2.1.4 on 2019-01-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0026_auto_20190108_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=50)),
                ('real_name', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank='true', null='true', upload_to='')),
                ('email', models.EmailField(max_length=120)),
                ('mins_left', models.FloatField(blank='true', default=10, null='true')),
                ('password', models.CharField(blank='true', default='pass12', max_length=30, null='true')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
