# Generated by Django 2.1.4 on 2019-01-09 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0030_auto_20190108_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reg_dtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 16, 3, 8, 696835)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='mins_left',
            field=models.FloatField(blank='true', default=10, null='true'),
        ),
    ]
