# Generated by Django 2.1.5 on 2019-01-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0031_auto_20190109_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mins_left',
            field=models.FloatField(blank='true', null='true'),
        ),
    ]
