# Generated by Django 2.1.5 on 2019-02-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0033_auto_20190130_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mins_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reg_dtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
