# Generated by Django 2.1.5 on 2019-02-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0035_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='no_of_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
