# Generated by Django 2.1.5 on 2019-02-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0036_auto_20190209_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reg_dtime',
        ),
        migrations.AlterField(
            model_name='profile',
            name='mins_left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/user_dp/'),
        ),
    ]
