# Generated by Django 2.1.5 on 2019-02-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0037_auto_20190210_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
